whi_joystick_hardware:
  loop_hz: 50 #hz
  data_topic: cmd_vel
  max_linear: 3.14 #m/s
  max_angular: 6.28 #rad/s
  ranges: [1951, 1951]
  buttons: {'reserved': 0x01, 'enable': 0x40}
  hardware: serial
  serial:
    name: smc60_one_button
    port: /dev/ttyUSB0
    baudrate: 115200
    device_id: 0x01
    data_head: 0xff
